REVERSE_GEOCODE_URL = "https://api.bigdatacloud.net/data/reverse-geocode"
LATITUDE            = "latitude"
LONGITUDE           = "longitude"
LANG                = "localityLanguage"
TOKEN               = "key"
AUTH_KEY            = "s0m3@uth-k3y"
